import Head from "next/head";
import HelloWorld from "../components/HelloWorld";
import TodoList from "../components/TodoList";
import CountrySelection from "../components/CountrySelection";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RTL and MSW demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HelloWorld />
        <TodoList />
        <CountrySelection />
      </main>
    </div>
  );
}
